spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
server:
  port: 8000
  address: 0.0.0.0
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: com.hackerearth.fullstack.backend.SQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlite:hackerearth.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
